a4: testA4.o miscFunctions.o queueFunctions.o helper.o
	gcc -Wall -std=c99 testA4.o -o a4 miscFunctions.o queueFunctions.o helper.o
	
testA4.o: testA4.c
	gcc -Wall -std=c99 -c testA4.c

miscFunctions.o: miscFunctions.c
	gcc -Wall -std=c99 -c miscFunctions.c

queueFunctions.o: queueFunctions.c
	gcc -Wall -std=c99 -c queueFunctions.c

helper.o: helper.c
	gcc -Wall -std=c99 -c helper.c

clean:
	rm * a4














